### ISSUE TITLE
Document.logger.warn does not get displayed during render - yaml2text

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-plugin-datastruct#16]
Steps to reproduce:

- pull https://github.com/CalConnect/csd-calendar-systems
- bundle exec metanorma -t iso sources/iso-34999.adoc

The original yaml file supplied in yaml2text block has some broken chars, the error gets thrown, caught here - https://github.com/metanorma/metanorma-plugin-datastruct/blob/master/lib/metanorma/plugin/datastruct/base_structured_text_preprocessor.rb#L117 but never gets disaplyed

**Comment by opoudjis** [comment]
There is no iso-34999 document in that repository, and I have been able to compile the iso-34300 document that is there without incident. Please provide correct file reference.

**Comment by w00lf** [comment]
> There is no iso-34999 document in that repository, and I have been able to compile the iso-34300 document that is there without incident. Please provide correct file reference.

i have created a test file in a separate branch

branch - hotfix/broken-logging

bundle exec metanorma -t iso spec/assets/broken_logging.adoc

**Comment by opoudjis** [comment]
Something went wrong with the 1.8.6 release of metanorma-iso: the CSS file was not generated, so Metanorma was trying to recompile it.

The 1.9.0 release I've just done has generated it correctly; so once I update metanorma-cli, this issue will go away.
