### ISSUE TITLE
Is there a reason for this gem to depend on metanorma?

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-datastruct#17]
I am trying to avoid circular dependencies in the metanorma stack, and to that end have just removed a dependency of isodoc on metanorma.

However, this gem and metanorma-plugin-lutaml depend on metanorma gem; and that reintroduced circular dependency in the stack, since they are now being required by metanorma-standoc.

If this dependency can be avoided, it needs to be.

**Comment by ronaldtse** [comment]
It doesn’t need to depend on metanorma.

**Comment by w00lf** [comment]
#18 removed dependency on metnorma, moved to dev deps @opoudjis
