### ISSUE TITLE
Gem not releasing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-datastruct#24]
https://github.com/metanorma/metanorma-plugin-datastruct/actions/runs/4644996886/jobs/8220586952

Something about MFA. Suspect I'm not even the gem owner, and GHA certainly doesn't think it is...

**Comment by CAMOBAP** [comment]
AFAIR we have two options here:
 - modify gemspec and set `rubygems_mfa_required` to `false` https://guides.rubygems.org/mfa-requirement-opt-in/
OR
 - Ask owners to enable MFA

@ronaldtse AFAIK we are did the second way for all our gems, I don't have access to do this, could you please help?

**Comment by opoudjis** [comment]
I will need to do manual release tomorrow if this is not resolved, it is dependency for standoc and is holding up release

**Comment by ronaldtse** [comment]
@CAMOBAP please do the first option for now, i.e. rubygems_mfa_required should be set to false.

**Comment by opoudjis** [comment]
I've released accordingly. I thought I had disabled MFA my side.
