### ISSUE TITLE
Enable access to document attributes within yaml2text block

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-plugin-datastruct#33]
In relation to https://github.com/metanorma/iso-10303-templates/pull/15#issuecomment-2061710982

Document attribute string values can be accessed by doing `{attribute}`, but inside a yaml2text block, it renders empty.

For example:

```adoc

= Document attributes
:edition: 10

== Clause

{edition} // renders 10

[yaml2text,...,data]
----
{edition} // empty
----


```

**Comment by ronaldtse** [comment]
How about this?

```
[yaml2text,...,data]
----
{% raw %}
{edition}
{% endraw %}
----
```

See more at: https://stackoverflow.com/questions/3330979/outputting-literal-curly-braces-in-liquid-templates

**Comment by manuelfuenmayor** [comment]
Thanks @ronaldtse! Yes, after some simple tweaks, I can work with this solution.

**Comment by ronaldtse** [comment]
Oh wow I see you've already fixed it. Thanks!
