### ISSUE TITLE
Do not raise error message if loading file doesn't not exit

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-plugin-datastruct#35]
As requested in https://github.com/metanorma/iso-10303/issues/226#issuecomment-2264516405.

Example:
```
[yaml2text,filename.yaml,context]
----
----
```

If `filename.yaml` doesn't exit, don't throw this error:

```
asciidoctor: WARNING: Liquid render error: Liquid error: internal
```

**Comment by ronaldtse** [comment]
The "FileNotFound" error should be made into a warning in the logging to console.

**Comment by ronaldtse** [comment]
@kwkwan can you please help handle this after the UML work? Thanks.

**Comment by kwkwan** [comment]
OK.  I will follow up this issue after the UML work.

**Comment by ronaldtse** [comment]
@kwkwan so what will happen when the file doesn't exist?

Does it:
* render no lines
* provide a warning message in the console?

**Comment by kwkwan** [comment]
> @kwkwan so what will happen when the file doesn't exist?
> 
> Does it:
> 
> * render no lines

Yes, it will render no lines

> * provide a warning message in the console?

The warning message will be logged in Asciidoctor::LoggerManager.logger.  Do you want to print the logged message on console by default?
